from __future__ import annotations

from dataclasses import dataclass
import hashlib
import json
import re
from typing import Any


KEYWORDS = {
    "formula": "fn",
    "ingredient": "let",
    "adjustable": "mut",
    "served": "pub",
    "chilled": "const",
    "can": "struct",
    "flavor": "enum",
    "recipe": "trait",
    "bottle": "impl",
    "taste": "match",
    "Batch": "Result",
    "Sealed": "Ok",
    "Recalled": "Err",
    "Supply": "Option",
    "Stocked": "Some",
    "Empty": "None",
}

PRELUDE = r'''// Generated by dietc. Edit the .dc source, not this file.
// Feed each stage's output into the first parameter of the next stage.
#[allow(unused_macros)]
macro_rules! production {
    ($value:expr => $stage:ident => $($rest:tt)+) => {
        production!($stage($value) => $($rest)+)
    };
    ($value:expr => $stage:ident($($args:expr),* $(,)?) => $($rest:tt)+) => {
        production!($stage($value, $($args),*) => $($rest)+)
    };
    ($value:expr => $stage:ident) => {
        $stage($value)
    };
    ($value:expr => $stage:ident($($args:expr),* $(,)?)) => {
        $stage($value, $($args),*)
    };
}

'''


class CompileError(ValueError):
    """A source-level error that dietc can report before invoking rustc."""


@dataclass(frozen=True)
class Guide:
    """Structured documentation attached to the item that follows it."""

    name: str
    purpose: str
    requires: tuple[str, ...] = ()
    ensures: tuple[str, ...] = ()
    examples: tuple[str, ...] = ()
    notes: tuple[str, ...] = ()
    line: int = 1

    def as_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "purpose": self.purpose,
            "requires": list(self.requires),
            "ensures": list(self.ensures),
            "examples": list(self.examples),
            "notes": list(self.notes),
            "line": self.line,
        }


@dataclass(frozen=True)
class GenerationRequest:
    """A reviewable work order for an AI code-generation tool."""

    name: str
    goal: str
    target: str = ""
    contexts: tuple[str, ...] = ()
    constraints: tuple[str, ...] = ()
    acceptance: tuple[str, ...] = ()
    output: str = ""
    mode: str = "create"
    line: int = 1

    def as_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "goal": self.goal,
            "target": self.target,
            "contexts": list(self.contexts),
            "constraints": list(self.constraints),
            "acceptance": list(self.acceptance),
            "output": self.output,
            "mode": self.mode,
            "line": self.line,
        }


@dataclass(frozen=True)
class Analysis:
    """Translated body plus the source's machine-readable development intent."""

    rust_body: str
    source_name: str
    source_sha256: str
    guides: tuple[Guide, ...]
    generation_requests: tuple[GenerationRequest, ...]

    def manifest(self) -> dict[str, Any]:
        return {
            "schema_version": 1,
            "language": "Diet Rust",
            "source": self.source_name,
            "source_sha256": self.source_sha256,
            "rust_compatibility": "stable Rust surface syntax",
            "guides": [guide.as_dict() for guide in self.guides],
            "generation_requests": [
                request.as_dict() for request in self.generation_requests
            ],
        }


@dataclass(frozen=True)
class _Delimiter:
    value: str
    line: int
    column: int


_IDENTIFIER = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")
_RAW_STRING = re.compile(r'(?:br|r)(?P<hashes>#{0,255})"')
_OPEN_TO_CLOSE = {"(": ")", "[": "]", "{": "}"}
_CLOSERS = set(_OPEN_TO_CLOSE.values())


def compile_source(source: str, source_name: str = "<memory>") -> str:
    """Translate one Diet Rust source unit to Rust.

    Translation is lexical: themed identifiers are changed only in code, never
    inside strings or comments. Rust remains responsible for parsing and type
    checking the generated program.
    """

    analysis = analyze_source(source, source_name)
    return compile_analysis(analysis)


def compile_analysis(analysis: Analysis) -> str:
    """Emit Rust from an already parsed Diet Rust analysis."""

    crate_preamble, body = _split_crate_preamble(analysis.rust_body)
    return crate_preamble + PRELUDE + body


def analyze_source(source: str, source_name: str = "<memory>") -> Analysis:
    """Translate and extract self-documentation and AI generation requests."""

    rust_body, guides, requests = _translate(source, source_name)
    return Analysis(
        rust_body=rust_body,
        source_name=source_name,
        source_sha256=hashlib.sha256(source.encode("utf-8")).hexdigest(),
        guides=tuple(guides),
        generation_requests=tuple(requests),
    )


def manifest_json(analysis: Analysis) -> str:
    """Serialize an analysis as the stable, machine-readable AI manifest."""

    return json.dumps(analysis.manifest(), indent=2, ensure_ascii=False) + "\n"


def render_generation_prompt(
    analysis: Analysis, source: str, request_name: str
) -> str:
    """Build a deterministic prompt packet for one declared generation job."""

    request = next(
        (item for item in analysis.generation_requests if item.name == request_name),
        None,
    )
    if request is None:
        available = ", ".join(item.name for item in analysis.generation_requests)
        suffix = f" Available requests: {available}." if available else ""
        raise CompileError(f"unknown generation request '{request_name}'.{suffix}")

    lines = [
        "# Diet Rust AI generation work order",
        "",
        f"Request: {request.name}",
        f"Mode: {request.mode}",
        f"Goal: {request.goal}",
    ]
    if request.target:
        lines.append(f"Target: {request.target}")
    if request.output:
        lines.append(f"Requested output: {request.output}")
    _prompt_list(lines, "Context", request.contexts)
    _prompt_list(lines, "Constraints", request.constraints)
    _prompt_list(lines, "Acceptance criteria", request.acceptance)

    if analysis.guides:
        lines.extend(["", "## Declared design guides"])
        for guide in analysis.guides:
            lines.append(f"- {guide.name}: {guide.purpose}")
            for guarantee in guide.ensures:
                lines.append(f"  - Guarantee: {guarantee}")

    lines.extend(
        [
            "",
            "## Generation protocol",
            "",
            "Preserve standard Rust ownership, borrowing, type safety, and public APIs.",
            "Do not introduce unsafe code unless the work order explicitly requires it.",
            "Return only the requested Diet Rust source, ready for review and compilation.",
            f"Source SHA-256: {analysis.source_sha256}",
            "",
            "## Current Diet Rust source",
            "",
            "```dietrust",
            source.rstrip(),
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def _prompt_list(lines: list[str], heading: str, values: tuple[str, ...]) -> None:
    if values:
        lines.extend(["", f"## {heading}"])
        lines.extend(f"- {value}" for value in values)


def _split_crate_preamble(source: str) -> tuple[str, str]:
    """Keep crate docs, inner attributes, and shebangs ahead of our macro item."""

    cursor = 0
    while cursor < len(source):
        if source[cursor].isspace():
            cursor += 1
            continue
        if cursor == 0 and source.startswith("#!", cursor) and not source.startswith(
            "#![", cursor
        ):
            newline = source.find("\n", cursor)
            cursor = len(source) if newline == -1 else newline + 1
            continue
        if source.startswith("//!", cursor):
            newline = source.find("\n", cursor)
            cursor = len(source) if newline == -1 else newline + 1
            continue
        if source.startswith("/*!", cursor):
            cursor = _block_comment_end(source, cursor, "<generated>", 1, 1)
            continue
        if source.startswith("//", cursor) and not source.startswith("///", cursor):
            newline = source.find("\n", cursor)
            cursor = len(source) if newline == -1 else newline + 1
            continue
        if source.startswith("/*", cursor) and not source.startswith("/**", cursor):
            cursor = _block_comment_end(source, cursor, "<generated>", 1, 1)
            continue
        if source.startswith("#![", cursor):
            cursor = _inner_attribute_end(source, cursor)
            continue
        break
    return source[:cursor], source[cursor:]


def _inner_attribute_end(source: str, start: int) -> int:
    depth = 1
    cursor = start + 3
    while cursor < len(source):
        if source.startswith("//", cursor):
            newline = source.find("\n", cursor)
            cursor = len(source) if newline == -1 else newline + 1
            continue
        if source.startswith("/*", cursor):
            cursor = _block_comment_end(source, cursor, "<generated>", 1, 1)
            continue
        raw_match = _RAW_STRING.match(source, cursor)
        if raw_match:
            terminator = '"' + raw_match.group("hashes")
            end = source.find(terminator, raw_match.end())
            if end == -1:
                raise CompileError("<generated>: unterminated raw string in attribute")
            cursor = end + len(terminator)
            continue
        if source[cursor] == '"':
            cursor = _quoted_end(source, cursor, '"', "<generated>", 1, 1)
            continue
        if source[cursor] == "[":
            depth += 1
        elif source[cursor] == "]":
            depth -= 1
            if depth == 0:
                return cursor + 1
        cursor += 1
    raise CompileError("<generated>: unterminated crate attribute")


def _translate(
    source: str, source_name: str
) -> tuple[str, list[Guide], list[GenerationRequest]]:
    output: list[str] = []
    delimiters: list[_Delimiter] = []
    guides: list[Guide] = []
    requests: list[GenerationRequest] = []
    index = 0
    line = 1
    column = 1

    def advance(text: str) -> None:
        nonlocal line, column
        newline_count = text.count("\n")
        if newline_count:
            line += newline_count
            column = len(text.rsplit("\n", 1)[-1]) + 1
        else:
            column += len(text)

    def append(text: str) -> None:
        output.append(text)
        advance(text)

    while index < len(source):
        # Line comments, including Rust doc comments.
        if source.startswith("//", index):
            end = source.find("\n", index)
            end = len(source) if end == -1 else end
            chunk = source[index:end]
            append(chunk)
            index = end
            continue

        # Nested block comments are legal in Rust.
        if source.startswith("/*", index):
            end = _block_comment_end(source, index, source_name, line, column)
            chunk = source[index:end]
            append(chunk)
            index = end
            continue

        # Raw and byte-raw strings.
        raw_match = _RAW_STRING.match(source, index)
        if raw_match:
            hashes = raw_match.group("hashes")
            terminator = '"' + hashes
            end = source.find(terminator, raw_match.end())
            if end == -1:
                raise CompileError(
                    f"{source_name}:{line}:{column}: unterminated raw string"
                )
            end += len(terminator)
            chunk = source[index:end]
            append(chunk)
            index = end
            continue

        # Ordinary and byte strings.
        string_prefix = 1 if source.startswith('b"', index) else 0
        if source[index + string_prefix : index + string_prefix + 1] == '"':
            end = _quoted_end(
                source, index + string_prefix, '"', source_name, line, column
            )
            chunk = source[index:end]
            append(chunk)
            index = end
            continue

        # Character literals. Lifetimes such as 'a are left as code.
        if source[index] == "'":
            char_end = _possible_char_end(source, index)
            if char_end is not None:
                chunk = source[index:char_end]
                append(chunk)
                index = char_end
                continue

        identifier = _IDENTIFIER.match(source, index)
        if identifier:
            original = identifier.group(0)
            if original in {"guide", "generate"}:
                metadata = _match_metadata_header(source, index, original)
                if metadata is not None:
                    name, open_brace = metadata
                    end = _metadata_block_end(
                        source, open_brace, source_name, line, column
                    )
                    fields = _parse_metadata_fields(
                        source,
                        open_brace + 1,
                        end - 1,
                        source_name,
                    )
                    if original == "guide":
                        guide = _make_guide(name, fields, source_name, line)
                        guides.append(guide)
                        replacement = _render_guide_docs(guide)
                    else:
                        request = _make_generation_request(
                            name, fields, source_name, line
                        )
                        requests.append(request)
                        replacement = (
                            f"// dietc AI generation request `{name}` is recorded "
                            "in the manifest.\n"
                        )
                    output.append(replacement)
                    advance(source[index:end])
                    index = end
                    continue
            # `label` is ordinary as an identifier and themed only as a macro.
            # This keeps fields such as `unit.label` valid.
            if original == "label" and _next_non_whitespace(source, identifier.end()) == "!":
                replacement = "println"
            else:
                replacement = KEYWORDS.get(original, original)
            output.append(replacement)
            advance(original)
            index = identifier.end()
            continue

        character = source[index]
        if character in _OPEN_TO_CLOSE:
            delimiters.append(_Delimiter(character, line, column))
        elif character in _CLOSERS:
            if not delimiters:
                raise CompileError(
                    f"{source_name}:{line}:{column}: unexpected '{character}'"
                )
            opening = delimiters.pop()
            expected = _OPEN_TO_CLOSE[opening.value]
            if character != expected:
                raise CompileError(
                    f"{source_name}:{line}:{column}: expected '{expected}' "
                    f"to close '{opening.value}' from "
                    f"{opening.line}:{opening.column}, found '{character}'"
                )

        append(character)
        index += 1

    if delimiters:
        opening = delimiters[-1]
        expected = _OPEN_TO_CLOSE[opening.value]
        raise CompileError(
            f"{source_name}:{opening.line}:{opening.column}: unclosed "
            f"'{opening.value}'; expected '{expected}'"
        )

    return "".join(output), guides, requests


def _match_metadata_header(
    source: str, start: int, kind: str
) -> tuple[str, int] | None:
    header = re.match(
        rf"{kind}[ \t\r\n]+([A-Za-z_][A-Za-z0-9_]*)[ \t\r\n]*\{{",
        source[start:],
    )
    if header is None:
        return None
    return header.group(1), start + header.end() - 1


def _metadata_block_end(
    source: str,
    open_brace: int,
    source_name: str,
    line: int,
    column: int,
) -> int:
    depth = 1
    cursor = open_brace + 1
    while cursor < len(source):
        if source.startswith("//", cursor):
            newline = source.find("\n", cursor)
            cursor = len(source) if newline == -1 else newline
            continue
        if source.startswith("/*", cursor):
            nested_line, nested_column = _line_column_at(source, cursor)
            cursor = _block_comment_end(
                source, cursor, source_name, nested_line, nested_column
            )
            continue
        raw_match = _RAW_STRING.match(source, cursor)
        if raw_match:
            hashes = raw_match.group("hashes")
            terminator = '"' + hashes
            end = source.find(terminator, raw_match.end())
            if end == -1:
                raise CompileError(
                    f"{source_name}:{line}:{column}: unterminated raw string "
                    "in metadata block"
                )
            cursor = end + len(terminator)
            continue
        if source[cursor] == '"':
            string_line, string_column = _line_column_at(source, cursor)
            cursor = _quoted_end(
                source,
                cursor,
                '"',
                source_name,
                string_line,
                string_column,
            )
            continue
        if source[cursor] == "{":
            depth += 1
        elif source[cursor] == "}":
            depth -= 1
            if depth == 0:
                return cursor + 1
        cursor += 1
    raise CompileError(
        f"{source_name}:{line}:{column}: unterminated metadata block; expected '}}'"
    )


def _parse_metadata_fields(
    source: str, start: int, end: int, source_name: str
) -> dict[str, list[str]]:
    fields: dict[str, list[str]] = {}
    cursor = start
    while True:
        cursor = _skip_metadata_trivia(source, cursor, end, source_name)
        if cursor >= end:
            return fields
        field_match = _IDENTIFIER.match(source, cursor, end)
        if field_match is None:
            _metadata_error(source, cursor, source_name, "expected a field name")
        field = field_match.group(0)
        cursor = _skip_metadata_trivia(
            source, field_match.end(), end, source_name
        )
        if cursor >= end or source[cursor] != ":":
            _metadata_error(
                source, cursor, source_name, f"expected ':' after '{field}'"
            )
        cursor = _skip_metadata_trivia(source, cursor + 1, end, source_name)
        value, cursor = _read_metadata_string(source, cursor, end, source_name)
        cursor = _skip_metadata_trivia(source, cursor, end, source_name)
        if cursor >= end or source[cursor] != ";":
            _metadata_error(
                source, cursor, source_name, f"expected ';' after '{field}'"
            )
        fields.setdefault(field, []).append(value)
        cursor += 1


def _skip_metadata_trivia(
    source: str, cursor: int, end: int, source_name: str
) -> int:
    while cursor < end:
        if source[cursor].isspace():
            cursor += 1
        elif source.startswith("//", cursor):
            newline = source.find("\n", cursor, end)
            cursor = end if newline == -1 else newline + 1
        elif source.startswith("/*", cursor):
            comment_line, comment_column = _line_column_at(source, cursor)
            cursor = _block_comment_end(
                source, cursor, source_name, comment_line, comment_column
            )
            if cursor > end:
                _metadata_error(
                    source, end, source_name, "comment crosses metadata boundary"
                )
        else:
            break
    return cursor


def _read_metadata_string(
    source: str, cursor: int, end: int, source_name: str
) -> tuple[str, int]:
    raw_match = _RAW_STRING.match(source, cursor, end)
    if raw_match:
        hashes = raw_match.group("hashes")
        terminator = '"' + hashes
        close = source.find(terminator, raw_match.end(), end)
        if close == -1:
            _metadata_error(source, cursor, source_name, "unterminated raw string")
        return source[raw_match.end() : close], close + len(terminator)
    if cursor >= end or source[cursor] != '"':
        _metadata_error(
            source, cursor, source_name, "metadata values must be string literals"
        )
    value_line, value_column = _line_column_at(source, cursor)
    string_end = _quoted_end(
        source, cursor, '"', source_name, value_line, value_column
    )
    if string_end > end:
        _metadata_error(source, cursor, source_name, "string crosses metadata boundary")
    token = source[cursor:string_end]
    try:
        return json.loads(token), string_end
    except json.JSONDecodeError as error:
        _metadata_error(
            source,
            cursor + error.pos,
            source_name,
            f"invalid metadata string: {error.msg}",
        )


def _make_guide(
    name: str,
    fields: dict[str, list[str]],
    source_name: str,
    line: int,
) -> Guide:
    _validate_metadata_fields(
        "guide",
        name,
        fields,
        allowed={"purpose", "requires", "ensures", "example", "note"},
        required={"purpose"},
        singular={"purpose"},
        source_name=source_name,
        line=line,
    )
    return Guide(
        name=name,
        purpose=fields["purpose"][0],
        requires=tuple(fields.get("requires", ())),
        ensures=tuple(fields.get("ensures", ())),
        examples=tuple(fields.get("example", ())),
        notes=tuple(fields.get("note", ())),
        line=line,
    )


def _make_generation_request(
    name: str,
    fields: dict[str, list[str]],
    source_name: str,
    line: int,
) -> GenerationRequest:
    _validate_metadata_fields(
        "generate",
        name,
        fields,
        allowed={
            "goal",
            "target",
            "context",
            "constraint",
            "acceptance",
            "output",
            "mode",
        },
        required={"goal"},
        singular={"goal", "target", "output", "mode"},
        source_name=source_name,
        line=line,
    )
    mode = fields.get("mode", ["create"])[0]
    if mode not in {"create", "extend", "replace", "tests", "docs"}:
        raise CompileError(
            f"{source_name}:{line}: generate '{name}' has unsupported mode "
            f"'{mode}'"
        )
    return GenerationRequest(
        name=name,
        goal=fields["goal"][0],
        target=fields.get("target", [""])[0],
        contexts=tuple(fields.get("context", ())),
        constraints=tuple(fields.get("constraint", ())),
        acceptance=tuple(fields.get("acceptance", ())),
        output=fields.get("output", [""])[0],
        mode=mode,
        line=line,
    )


def _validate_metadata_fields(
    kind: str,
    name: str,
    fields: dict[str, list[str]],
    *,
    allowed: set[str],
    required: set[str],
    singular: set[str],
    source_name: str,
    line: int,
) -> None:
    unknown = set(fields) - allowed
    if unknown:
        field = sorted(unknown)[0]
        raise CompileError(
            f"{source_name}:{line}: unknown {kind} field '{field}' in '{name}'"
        )
    missing = required - set(fields)
    if missing:
        field = sorted(missing)[0]
        raise CompileError(
            f"{source_name}:{line}: {kind} '{name}' requires field '{field}'"
        )
    duplicate = next(
        (field for field in singular if len(fields.get(field, ())) > 1), None
    )
    if duplicate:
        raise CompileError(
            f"{source_name}:{line}: {kind} '{name}' repeats singular field "
            f"'{duplicate}'"
        )


def _render_guide_docs(guide: Guide) -> str:
    lines = [f"/// # Diet Rust guide: `{guide.name}`", "///", f"/// {guide.purpose}"]
    sections = (
        ("Requires", guide.requires),
        ("Guarantees", guide.ensures),
        ("Examples", guide.examples),
        ("Notes", guide.notes),
    )
    for heading, values in sections:
        if values:
            lines.extend(["///", f"/// ## {heading}"])
            for value in values:
                value_lines = value.splitlines() or [""]
                lines.append(f"/// - {value_lines[0]}")
                lines.extend(f"///   {part}" for part in value_lines[1:])
    return "\n".join(lines) + "\n"


def _metadata_error(
    source: str, offset: int, source_name: str, message: str
) -> None:
    line, column = _line_column_at(source, min(offset, len(source)))
    raise CompileError(f"{source_name}:{line}:{column}: {message}")


def _line_column_at(source: str, offset: int) -> tuple[int, int]:
    line = source.count("\n", 0, offset) + 1
    last_newline = source.rfind("\n", 0, offset)
    return line, offset - last_newline


def _block_comment_end(
    source: str, start: int, source_name: str, line: int, column: int
) -> int:
    depth = 1
    cursor = start + 2
    while cursor < len(source) and depth:
        if source.startswith("/*", cursor):
            depth += 1
            cursor += 2
        elif source.startswith("*/", cursor):
            depth -= 1
            cursor += 2
        else:
            cursor += 1
    if depth:
        raise CompileError(
            f"{source_name}:{line}:{column}: unterminated block comment"
        )
    return cursor


def _quoted_end(
    source: str,
    quote_index: int,
    quote: str,
    source_name: str,
    line: int,
    column: int,
) -> int:
    cursor = quote_index + 1
    escaped = False
    while cursor < len(source):
        character = source[cursor]
        if escaped:
            escaped = False
        elif character == "\\":
            escaped = True
        elif character == quote:
            return cursor + 1
        cursor += 1
    raise CompileError(f"{source_name}:{line}:{column}: unterminated string literal")


def _possible_char_end(source: str, start: int) -> int | None:
    cursor = start + 1
    if cursor >= len(source) or source[cursor] in "\r\n'":
        return None
    if source[cursor] == "\\":
        cursor += 2
    else:
        cursor += 1
    if cursor < len(source) and source[cursor] == "'":
        return cursor + 1
    return None


def _next_non_whitespace(source: str, start: int) -> str | None:
    cursor = start
    while cursor < len(source) and source[cursor].isspace():
        cursor += 1
    return source[cursor] if cursor < len(source) else None
